import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import squarify

def eda_page(data, data_expanded):
    st.title("Exploratory Data Analysis (EDA)")

    # Summary Statistics for Numerical Columns
    st.subheader("Summary Statistics for Numerical Columns")
    numerical_cols = ['ordered_quantity', 'unit_selling_price', 'unit_list_price']
    summary_stats = data[numerical_cols].describe()
    st.write(summary_stats)
    
    # Categorical Distribution
    st.subheader("Categorical Distribution")
    def display_categorical_distribution(df, column_name):
        categorical_dist = df[column_name].value_counts()
        st.write(f"Distribution of {column_name}:")
        st.write(categorical_dist)
    
    display_categorical_distribution(data, 'operating_unit_name')
    
    # Sales Analysis Section
    st.header("Sales Analysis")
    
    # Top 10 Best-Selling Products
    st.subheader("Top 10 Best-Selling Products")
    col1, col2 = st.columns([1, 1])  # Create two columns with ratios
    with col1:
        def plot_top_products(df):
            top_products = df[df['product_name'] != 'Product Not Found']\
                            .groupby('product_name')['ordered_quantity']\
                            .sum().sort_values(ascending=False).head(10)
            fig, ax = plt.subplots(figsize=(6, 6))
            top_products.plot(kind='bar', ax=ax)
            ax.set_title('Top 10 Best-Selling Products')
            ax.set_xlabel('Product Name')
            ax.set_ylabel('Total Quantity Sold')
            ax.set_xticklabels(top_products.index, rotation=45, ha='right')
            plt.tight_layout()
            st.pyplot(fig)
        plot_top_products(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Top 10 Best-Selling Products' plot shows the products with the highest sales volume. <br><br> This visualization highlights the top-performing products in terms of quantity sold, providing insights into customer preferences and popular items.</p>",
            unsafe_allow_html=True
        )
    
    # Monthly Sales Trend
    st.subheader("Monthly Sales Trend")
    col1, col2 = st.columns([1, 1])

    with col1:
        def plot_monthly_sales_trend(df):
            # Ensure 'ordered_date' is in datetime format
            df['ordered_date'] = pd.to_datetime(df['ordered_date'], errors='coerce')
            
            # Check for null values after conversion
            if df['ordered_date'].isnull().any():
                st.error("Some 'ordered_date' values could not be converted to datetime.")
                return
            
            # Create the 'year_month' column
            df['year_month'] = df['ordered_date'].dt.to_period('M')
            
            # Group by 'year_month' and calculate the total sales
            monthly_sales = df.groupby('year_month')['total_sales_with_discount'].sum()
            
            # Format the index as 'Month Year'
            monthly_sales.index = monthly_sales.index.strftime('%B %Y')
            
            # Plot the bar chart
            fig, ax = plt.subplots(figsize=(6, 4))
            monthly_sales.plot(kind='barh', ax=ax)
            ax.set_title('Monthly Sales Trend')
            ax.set_xlabel('Total Sales with Discount')
            ax.set_ylabel('Month')
            plt.tight_layout()
            st.pyplot(fig)
    
    plot_monthly_sales_trend(data)
    
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Monthly Sales Trend' plot displays the total sales revenue for each month. <br><br> It helps in understanding the sales performance over time, identifying peak sales periods, and evaluating seasonal trends or patterns.</p>",
            unsafe_allow_html=True
        )
    
    # Revenue Contribution by Product Category
    st.subheader("Revenue Contribution by Product Category")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_category_sales(df):
            category_sales = df.groupby('product_category')['total_sales_with_discount'].sum().sort_values(ascending=False)
            fig, ax = plt.subplots(figsize=(10, 5))
            category_sales.plot(kind='bar', ax=ax)
            ax.set_title('Revenue Contribution by Product Category')
            ax.set_xlabel('Product Category')
            ax.set_ylabel('Total Sales')
            ax.set_xticklabels(category_sales.index, rotation=45, ha='right', fontsize=8)
            ax.grid(False)
            plt.tight_layout()
            st.pyplot(fig)
        plot_category_sales(data_expanded)
    
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Revenue Contribution by Product Category' plot shows the percentage of total revenue generated by each product category. <br><br> It highlights the most financially significant categories and helps identify which ones drive the most revenue.</p>",
            unsafe_allow_html=True
        )
    
    # Distribution of Order Quantities
    st.subheader("Distribution of Order Quantities")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_order_quantity_distribution(df):
            fig, ax = plt.subplots(figsize=(6, 4))
            df['ordered_quantity'].plot(kind='hist', bins=30, ax=ax)
            ax.set_title('Distribution of Order Quantities')
            ax.set_xlabel('Order Quantity')
            ax.set_ylabel('Frequency')
            max_order_quantity = df['ordered_quantity'].max()
            ax.set_xticks(range(0, max_order_quantity + 1, 5))
            plt.tight_layout()
            st.pyplot(fig)
        plot_order_quantity_distribution(data)
    
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Distribution of Order Quantities' plot is a histogram that visualizes the frequency of various order quantities placed by customers. <br><br> It provides insight into purchasing behavior by showing how many items are typically ordered in a single transaction. <br><br> This histogram helps identify common order sizes, revealing whether customers typically buy single items or larger quantities.</p>",
            unsafe_allow_html=True
        )
    
    # Monetary Distribution
    st.subheader("Monetary Distribution")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_monetary_distribution(df):
            monetary = df.groupby('ecom_reference_order_number')['total_sales_with_discount'].sum()
            rfm = pd.DataFrame({'monetary': monetary})
            fig, ax = plt.subplots(figsize=(6, 4))
            sns.histplot(rfm, x='monetary', kde=True, ax=ax)
            ax.set_title('Monetary Distribution')
            ax.set_xlabel('Total Spend')
            ax.set_ylabel('Frequency')
            plt.tight_layout()
            st.pyplot(fig)
        plot_monetary_distribution(data)
    
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Monetary Distribution' plot is a histogram that displays the distribution of total spending per order, showing the frequency of different spending levels by customers. <br><br> It helps to understand the monetary value of transactions, indicating how much customers typically spend in a single purchase.</p>",
            unsafe_allow_html=True
        )
    
    # Order Analysis Section
    st.header("Order Analysis")
    
    # Recency Distribution
    st.subheader("Recency Distribution")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_recency_distribution(df):
            df['recency'] = (df['ordered_date'].max() - df['ordered_date']).dt.days
            rfm = pd.DataFrame({'recency': df.groupby('ecom_reference_order_number')['recency'].min()})
            fig, ax = plt.subplots(figsize=(6, 4))
            sns.histplot(rfm, x='recency', kde=True, ax=ax)
            ax.set_title('Recency Distribution')
            ax.set_xlabel('Days Since Last Purchase')
            ax.set_ylabel('Frequency')
            plt.tight_layout()
            st.pyplot(fig)
        plot_recency_distribution(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Recency Distribution' plot is a histogram that illustrates the distribution of the number of days since the last recorded order. <br><br> This plot provides insight into order activity by showing how recently orders have been placed. The x-axis represents the number of days since the last order, while the y-axis shows the frequency of order IDs falling into each recency category. <br><br> Although this data does not directly track individual customers, it still offers valuable information about the frequency and timing of orders. </p>",
            unsafe_allow_html=True
        )


    # Order Quantity Statistics Section
    st.subheader("Order Quantity Statistics")
    # Create columns for layout
    col1, col2 = st.columns([1, 1])  # Adjust the column width ratios as needed
    with col1:
        # Function to display order quantity statistics
        def display_order_quantity_stats(df):
            order_quantity_stats = df.groupby('ecom_reference_order_number')['ordered_quantity'].sum()
            summary_stats = order_quantity_stats.describe()

            stats = {
                'Statistic': ['Average', 'Minimum', 'Maximum', 'Q1 (25th percentile)', 'Median (50th percentile)', 'Q3 (75th percentile)'],
                'Value': [
                    summary_stats['mean'],
                    summary_stats['min'],
                    summary_stats['max'],
                    summary_stats['25%'],
                    summary_stats['50%'],
                    summary_stats['75%']
                ]
            }
            stats_df = pd.DataFrame(stats)
            st.table(stats_df)

        display_order_quantity_stats(data)
        with col2:
            st.markdown(
                "<p style='font-size:20px'> The 'Order Quantity Statistics' table presents summary statistics for the quantity of items ordered per transaction. <br><br> It provides key metrics such as the average, minimum, maximum, median, and quartiles (Q1 and Q3) of the total items ordered in each transaction. <br><br> This table offers a comprehensive overview of order sizes, highlighting typical order quantities, the range of quantities ordered, and the distribution's central tendency and spread.</p>",
                unsafe_allow_html=True
            )



    # Distribution of Items per Order
    st.subheader("Distribution of Items per Order")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_items_per_order_distribution(df):
            order_quantity_stats = df.groupby('ecom_reference_order_number')['ordered_quantity'].sum()
            fig, ax = plt.subplots(figsize=(6, 4))
            order_quantity_stats.plot(kind='hist', bins=30, alpha=0.7, ax=ax)
            ax.set_title('Distribution of Items per Order')
            ax.set_xlabel('Number of Items per Order')
            ax.set_ylabel('Frequency')
            plt.tight_layout()
            st.pyplot(fig)
        plot_items_per_order_distribution(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Distribution of Items per Order' plot is a histogram that visualizes the frequency of different quantities of items ordered in a single transaction. <br><br> It shows how many transactions include specific numbers of items, providing insight into typical order sizes. <br><br> This plot helps identify common order sizes, whether customers often purchase single items or multiple items, and the overall distribution of items per transaction. </p>",
            unsafe_allow_html=True
        )
    
    # Pricing and Discount Analysis Section
    st.header("Pricing and Discount Analysis")

    # Distribution of Selling Prices and List Prices
    st.subheader("Distribution of Selling Prices and List Prices")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_price_distribution(df):
            fig, ax = plt.subplots(figsize=(6, 4))
            df['unit_selling_price'].plot(kind='hist', bins=20, alpha=0.5, label='Selling Price', ax=ax)
            df['unit_list_price'].plot(kind='hist', bins=20, alpha=0.5, label='List Price', ax=ax)
            ax.set_title('Distribution of Selling Prices and List Prices')
            ax.set_xlabel('Price')
            ax.set_ylabel('Frequency')
            ax.legend()
            plt.tight_layout()
            st.pyplot(fig)
        plot_price_distribution(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Distribution of Selling Prices and List Prices' plot is a histogram that shows the frequency distribution of both the selling prices and list prices of products. <br><br> The plot helps to understand the range and distribution of prices at which products are sold (selling price) compared to their original or undiscounted prices (list price). </p>",
            unsafe_allow_html=True
        )

    # Distribution of Discount Percentages
    st.subheader("Distribution of Discount Percentages")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_discount_percentage_distribution(df):
            df['discount_percentage'] = (df['unit_list_price'] - df['unit_selling_price']) / df['unit_list_price'] * 100
            fig, ax = plt.subplots(figsize=(6, 4))
            df['discount_percentage'].plot(kind='hist', bins=20, ax=ax)
            ax.set_title('Distribution of Discount Percentages')
            ax.set_xlabel('Discount Percentage')
            ax.set_ylabel('Frequency')
            plt.tight_layout()
            st.pyplot(fig)
        plot_discount_percentage_distribution(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Distribution of Discount Percentages' plot is a histogram that displays the frequency distribution of discount percentages applied to products. <br><br> It provides insight into the range and prevalence of discounts offered on products. <br><br> This plot helps to identify common discount levels and the extent of price reductions across the product range. </p>",
            unsafe_allow_html=True
        )


    # Discount Percentage by Category
    st.subheader("Discount Percentage by Category")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_discount_percentage_by_category(df):
            df['discount_percentage'] = (df['unit_list_price'] - df['unit_selling_price']) / df['unit_list_price'] * 100
            fig, ax = plt.subplots(figsize=(10, 6))
            sns.boxplot(x='product_category', y='discount_percentage', data=df, width=0.5, ax=ax)
            ax.set_title('Discount Percentage by Category')
            ax.set_xlabel('Product Category')
            ax.set_ylabel('Discount Percentage')
            ax.set_xticklabels(df['product_category'].unique(), rotation=90, ha='right')
            plt.tight_layout()
            st.pyplot(fig)
        plot_discount_percentage_by_category(data_expanded)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Discount Percentage by Category' plot shows the variation in discount percentages across different product categories. <br><br> This visualization helps to understand how discounting strategies differ between categories and which categories offer higher or lower discounts. </p>",
            unsafe_allow_html=True
        )

    # Scatter Plot of Discount Percentage vs. Ordered Quantity
    st.subheader("Scatter Plot of Discount Percentage vs. Ordered Quantity")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_discount_vs_ordered_quantity(df):
            df['discount_percentage'] = (df['unit_list_price'] - df['unit_selling_price']) / df['unit_list_price'] * 100
            correlation = df['discount_percentage'].corr(df['ordered_quantity'])
            fig, ax = plt.subplots(figsize=(6, 4))
            sns.scatterplot(x='discount_percentage', y='ordered_quantity', data=df, alpha=0.6, ax=ax)
            ax.set_title('Scatter Plot of Discount Percentage vs. Ordered Quantity')
            ax.set_xlabel('Discount Percentage')
            ax.set_ylabel('Ordered Quantity')
            ax.grid(True)
            ax.text(0.05, max(df['ordered_quantity']) * 0.95, f'Correlation: {correlation:.2f}', fontsize=12, color='red')
            plt.tight_layout()
            st.pyplot(fig)
        plot_discount_vs_ordered_quantity(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Scatter Plot of Discount Percentage vs. Ordered Quantity' shows the relationship between the discount percentage applied to products and the quantity ordered. <br><br> It helps to analyze whether higher discounts correlate with higher sales volumes, providing insights into the effectiveness of discount strategies </p>",
            unsafe_allow_html=True
        )

    # Comparison of Average Discounts for Popular and Less Popular Items
    st.subheader("Comparison of Average Discounts for Popular and Less Popular Items")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_average_discounts_comparison_hist(df):
            item_popularity = df.groupby('product_name')['ordered_quantity'].sum()
            median_popularity = item_popularity.median()
            df['popularity'] = df['product_name'].map(lambda x: 'Popular' if item_popularity[x] > median_popularity else 'Less Popular')
            average_discounts = df.groupby('product_name')['discount_percentage'].mean()
            df['average_discount'] = df['product_name'].map(average_discounts)

            comparison_df = df[['product_name', 'popularity', 'average_discount']].drop_duplicates()
            fig, ax = plt.subplots(figsize=(6, 4))
            sns.histplot(data=comparison_df, x='average_discount', hue='popularity', element='step', stat='density', common_norm=False, bins=20, ax=ax)
            ax.set_title('Comparison of Average Discounts for Popular and Less Popular Items')
            ax.set_xlabel('Average Discount Percentage')
            ax.set_ylabel('Density')
            plt.tight_layout()
            st.pyplot(fig)
        plot_average_discounts_comparison_hist(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Comparison of Average Discounts for Popular and Less Popular Items' plot is a histogram that compares the average discount percentages applied to popular and less popular items. <br><br> The items are categorized based on their sales volume, with 'popular' items having sales above the median and 'less popular' items below. <br><br> This plot helps to understand how discount strategies vary based on product popularity, showing the distribution of average discounts for each category. It provides insight into whether popular or less popular items receive larger discounts on average. </p>",
            unsafe_allow_html=True
        )

    # Box Plot of Unit Selling Prices by Top Performing Product Categories
    st.subheader("Box Plot of Unit Selling Prices by Top Performing Product Categories")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_top_categories_unit_selling_prices(df):
            df['total_sales_with_discount'] = df['ordered_quantity'] * df['unit_selling_price']
            category_sales = df.groupby('product_category')['total_sales_with_discount'].sum()
            top_categories = category_sales.sort_values(ascending=False).head(10).index.tolist()
            top_categories_df = df[df['product_category'].isin(top_categories)]

            fig, ax = plt.subplots(figsize=(8, 6))
            sns.boxplot(x='product_category', y='unit_selling_price', data=top_categories_df, order=top_categories, ax=ax)
            ax.set_title('Box Plot of Unit Selling Prices by Top Performing Product Categories')
            ax.set_xlabel('Product Category')
            ax.set_ylabel('Unit Selling Price')
            ax.set_xticklabels(top_categories, rotation=90)
            plt.tight_layout()
            st.pyplot(fig)
        plot_top_categories_unit_selling_prices(data_expanded)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Box Plot of Unit Selling Prices by Top Performing Product Categories' visualizes the range and distribution of unit selling prices across the top-performing product categories. <br><br> This plot provides insight into the pricing strategies within these categories, highlighting price variations and the median price point. </p>",
            unsafe_allow_html=True
        )
    
    # Supply Chain Analysis Section
    st.header("Supply Chain Analysis")

    # Top Distributing Companies by Quantity Shipped
    st.subheader("Top Distributing Companies by Quantity Shipped")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_top_distributors_treemap(df):
            top_distributors = df.groupby('operating_unit_name')['ordered_quantity'].sum().sort_values(ascending=False).head(10)
            colors = plt.cm.Blues(range(0, 256, int(256/len(top_distributors))))
            colors = colors[::-1]  # Reverse the colors
            fig, ax = plt.subplots(figsize=(6, 4))
            squarify.plot(sizes=top_distributors.values, label=top_distributors.index, alpha=0.8, color=colors, ax=ax)
            ax.set_title('Top Distributing Companies by Quantity Shipped')
            plt.axis('off')  # Remove axes
            plt.tight_layout()
            st.pyplot(fig)
        plot_top_distributors_treemap(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Top Distributing Companies by Quantity Shipped' treemap visualizes the quantity of items shipped by each distributor. It provides a clear view of the most active distribution companies, showing their relative contribution to the total shipments. <br><br> This visualization helps to understand the role and impact of different distributors in the supply chain. </p>",
            unsafe_allow_html=True
        )
    
    # Product Positioning Section
    st.header("Product Positioning")
    
    # Distribution of the Number of Items per Transaction
    st.subheader("Distribution of the Number of Items per Transaction")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_transaction_diversity(df):
            basket = (df
                    .groupby(['ecom_reference_order_number', 'product_name'])['product_name']
                    .count().unstack().reset_index().fillna(0)
                    .set_index('ecom_reference_order_number'))
            basket_sets = basket.applymap(lambda x: 1 if x > 0 else 0)
            unique_items_per_transaction = basket_sets.sum(axis=1)

            fig, ax = plt.subplots(figsize=(6, 4))
            ax.hist(unique_items_per_transaction, bins=range(1, unique_items_per_transaction.max() + 1), edgecolor='k')
            ax.set_title('Distribution of the Number of Items per Transaction')
            ax.set_xlabel('Number of Items per Transaction')
            ax.set_ylabel('Frequency')
            plt.tight_layout()
            st.pyplot(fig)
        plot_transaction_diversity(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Transaction Diversity' plot shows the diversity in transactions by displaying the number of unique items purchased in each transaction. <br><br> It helps to understand whether customers are buying a wide variety of products or focusing on a few specific items. </p>",
            unsafe_allow_html=True
        )

    # Distribution of Item Frequencies
    st.subheader("Distribution of Item Frequencies")
    col1, col2 = st.columns([1, 1])
    with col1:
        def plot_item_frequencies(df):
            basket = (df
                    .groupby(['ecom_reference_order_number', 'product_name'])['product_name']
                    .count().unstack().reset_index().fillna(0)
                    .set_index('ecom_reference_order_number'))
            basket_sets = basket.applymap(lambda x: 1 if x > 0 else 0)
            item_frequencies = basket_sets.sum(axis=0)

            fig, ax = plt.subplots(figsize=(6, 4))
            ax.hist(item_frequencies, bins=range(1, item_frequencies.max() + 1), edgecolor='k')
            ax.set_title('Distribution of Item Frequencies')
            ax.set_xlabel('Frequency of Items')
            ax.set_ylabel('Number of Items')
            plt.tight_layout()
            st.pyplot(fig)
        plot_item_frequencies(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Distribution of Item Frequencies' plot shows how frequently each product is purchased. <br><br> This plot provides insight into product popularity and helps identify which products are commonly bought together. </p>",
            unsafe_allow_html=True
        )

    # Transaction Diversity Statistics
    st.subheader("Transaction Diversity Statistics")
    col1, col2 = st.columns([1, 1])
    with col1:
        def save_transaction_diversity_stats(df):
            basket = (df
                      .groupby(['ecom_reference_order_number', 'product_name'])['product_name']
                      .count().unstack().reset_index().fillna(0)
                      .set_index('ecom_reference_order_number'))
            basket_sets = basket.applymap(lambda x: 1 if x > 0 else 0)
            unique_items_per_transaction = basket_sets.sum(axis=1)
            stats = unique_items_per_transaction.describe()
            stats_df = pd.DataFrame(stats, columns=['Value']).reset_index()
            stats_df.columns = ['Statistic', 'Value']
            st.table(stats_df)
        save_transaction_diversity_stats(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> The 'Transaction Diversity Statistics' table presents summary statistics regarding the number of unique items purchased per transaction. <br><br> It provides key metrics such as the mean, median, minimum, maximum, and quartiles (Q1 and Q3) of the unique items in each transaction. <br><br> This table offers an overview of how varied customer purchases are in terms of product diversity within a single transaction. </p>",
            unsafe_allow_html=True
        )

    # Item Frequencies Statistics
    st.subheader("Item Frequencies Statistics")
    col1, col2 = st.columns([1, 1])
    with col1:
        def save_item_frequencies_stats(df):
            basket = (df
                      .groupby(['ecom_reference_order_number', 'product_name'])['product_name']
                      .count().unstack().reset_index().fillna(0)
                      .set_index('ecom_reference_order_number'))
            basket_sets = basket.applymap(lambda x: 1 if x > 0 else 0)
            item_frequencies = basket_sets.sum(axis=0)
            stats = item_frequencies.describe()
            stats_df = pd.DataFrame(stats, columns=['Value']).reset_index()
            stats_df.columns = ['Statistic', 'Value']
            st.table(stats_df)
        save_item_frequencies_stats(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> The 'Item Frequency Statistics' table provides summary statistics on how frequently each item is purchased across all transactions. <br><br> It includes key metrics such as the mean, median, minimum, maximum, and quartiles (Q1 and Q3) for the frequency of item purchases. This table offers insights into the popularity of different products, highlighting how often items are bought on average, the range of purchase frequencies, and the distribution of these frequencies. </p>",
            unsafe_allow_html=True
        )

    # Considered as Niche Products
    st.subheader("Considered as Niche Products")
    col1, col2 = st.columns([1, 1])
    with col1:
        def save_combined_niche_products_count(df):
            sales_volume = df.groupby('product_name')['ordered_quantity'].sum().reset_index()
            niche_products = sales_volume[sales_volume['ordered_quantity'] < sales_volume['ordered_quantity'].quantile(0.25)]
            purchase_frequency = df.groupby('product_name')['ecom_reference_order_number'].nunique().reset_index()
            niche_purchase_frequency = purchase_frequency[purchase_frequency['ecom_reference_order_number'] < purchase_frequency['ecom_reference_order_number'].quantile(0.25)]

            combined_niche_products = set(niche_products['product_name']).intersection(
                set(niche_purchase_frequency['product_name'])
            )

            combined_niche_products_df = pd.DataFrame({
                'Product Name': list(combined_niche_products)
            })

            st.table(combined_niche_products_df)
        save_combined_niche_products_count(data)
    with col2:
        st.markdown(
            "<p style='font-size:20px'> <br> The 'Considered as Niche Products' section lists products identified as niche based on specific criteria. <br><br> These products are less frequently purchased but may cater to specific customer segments or interests. <br><br> Understanding niche products helps in targeting niche markets and optimizing inventory </p>",
            unsafe_allow_html=True
        )

    # Footer
    st.markdown("""
    <div style="position: fixed; bottom: 10px; right: 10px; font-size:20px; color:gray;">
        To Malia Group, By AUB Students
    </div>
    """, unsafe_allow_html=True)
